name: NumPy

# Controls when the action will run.
on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/numpy.yml'

  schedule:
  #        ┌───────────── minute (0 - 59)
  #        │ ┌───────────── hour (0 - 23)
  #        │ │ ┌───────────── day of the month (1 - 31)
  #        │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
  #        │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
  #        │ │ │ │ │
  - cron: "0 2 * * 0"

jobs:
  numpy:
    name: NumPy ${{ matrix.os }}/${{ matrix.python_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-11, windows-latest]
        python_version: [pypy-3.9-nightly]

    timeout-minutes: 90

    steps:
    - uses: actions/checkout@v3
      with:
        repository: numpy/numpy
        path: repo
        submodules: recursive
        fetch-depth: 0

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python_version }}

    - name: Show compiler version
      run: |
        gcc --version
      if: matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest'

    - name: Install NumPy
      run: |
        cd repo
        python -m pip install --upgrade pip
        python -m pip install -r test_requirements.txt
        python -m pip install .
        # change out of the repo directory so we can import numpy cleanly
        mkdir -p ../test
        cd ../test
        python -c "import numpy, sys; sys.exit(not numpy.test('full', verbose=3))"
