name: pytest-html

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  schedule:
  #        ┌───────────── minute (0 - 59)
  #        │ ┌───────────── hour (0 - 23)
  #        │ │ ┌───────────── day of the month (1 - 31)
  #        │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
  #        │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
  #        │ │ │ │ │
  - cron: "0 2 * * 0"

jobs:
  test_python:
    name: pytest-html ${{ matrix.name }} ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: pypy3-ubuntu
            python-version: pypy-3.8

          - os: windows-latest
            name: pypy3-windows
            python-version: pypy-3.8

          - os: ubuntu-latest
            name: pypy3-nightly-ubuntu
            python-version: pypy-3.8-nightly

          - os: windows-latest
            name: pypy3-nightly-windows
            python-version: pypy-3.8-nightly

    steps:
      - uses: actions/checkout@v3
        with:
          repository: pytest-dev/pytest-html

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix['python-version'] }}

      - name: Install tox
        run: python -m pip install --upgrade pip tox wheel "setuptools==56.0"

      - name: Get Tox Environment Name From Matrix Name
        uses: rishabhgupta/split-by@v1
        id: split-matrix-name
        with:
          string: '${{ matrix.name }}'
          split-by: '-'

      - name: Test with tox
        run: |
          echo PWD $PWD
          mkdir -p .tox/dist
          python -m tox -e ${{ steps.split-matrix-name.outputs._0}}-cov

